server:
  port: 8082

spring:
  application:
    name: ollama

  ai:

    openai:
      base-url: https://generativelanguage.googleapis.com
      api-key: ${GEMENI}


      chat:
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash
          max-tokens: 100000
          temperature: 0


  datasource:
    url: jdbc:postgresql://localhost:5432/ofk
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

vaadin:
  push:
    enabled: true